# Generated by Django 4.1.4 on 2022-12-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suvigya", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="date",
        ),
    ]
